defaults:
  - sparse_lightningdit_v3_xl1
  - _self_

_target_: models.sparse_lightningdit_v3_cross_attn_varlen_img_text.SparseLightningDiTV3CrossAttnVarlenImgText

block_type: "v1"
image_encoder_name: facebook/dinov2-large
text_encoder_name: openai/clip-vit-large-patch14