defaults:
  - gpf_text
  - _self_

_target_: models.sparse_lightningdit_v3_cross_attn_varlen_img_text_v2.SparseLightningDiTV3CrossAttnVarlenImgTextV2

image_encoder_name: facebook/dinov2-large
freeze_everything: True
