_target_: models.sparse_lightningdit_v3.SparseLightningDiTV3
depth: 28
hidden_size: 1152
num_heads: 16
use_qknorm: false
use_swiglu: true
use_rope: false
use_rmsnorm: true
wo_shift: false
in_channels: 6
use_checkpoint: false
backend: flash-attn