_target_: models.sparse_lightningdit_v3.SparseLightningDiTV3
depth: 24
hidden_size: 1024
num_heads: 16
use_qknorm: false
use_swiglu: true
use_rope: false
use_face_emebds: false
use_rmsnorm: true
wo_shift: false
in_channels: 6
use_checkpoint: false
backend: flash-attn
num_face_classes: 34