defaults:
  - sparselightningdit_xl_garment_particle_fsdp2
  - override dataset: garment_particles_v2.2_w_text
  - override model: sparse_lightningdit_v3_xl1_w_text_fsdp2
  - _self_

data:
  val_split: "assets/garment_particle_v2_test_11182025.txt"
  train_split: "assets/garment_particle_v2_train_11182025.txt"     
  sampler:
    token_counts_cache: assets/token_counts_v2.2.pkl                                         #       if you just want to inference, download our latent_status.safetensors and give its folder path here is ok.

# recommend to use default settings
train:
  exp_name: 'xl1_v2.2_w_text' # <---- experiment name, set as you like
