dataset:
  normalization:
    pcd_mean:
    - 1.02373453
    - 0.53175375
    - 0.0537376513
    - 86.1824935
    - -1.33205849
    - 0.0
    pcd_std:
    - 0.51201646
    - 0.13567009
    - 17.43921292
    - 36.19954752
    - 9.72246543
    - 1.0
    xlims:
    - -150
    - 150
    ylims:
    - -80
    - 220
    transformation_mean:
    - 145.16962989
    - 86.01913585
    - -0.0125378371
    - 113.507532
    - 2.63046369
    - 0
    - 0
    - 0
    transformation_std:
    - 157.87811579
    - 42.82879761
    - 26.06867645
    - 32.42920198
    - 22.29905009
    - 1
    - 1
    - 1
    edge_mean:
    - 2.3970279360541352e-18
    - -1.9892348017046765e-19
    - 0.09893195163130523
    - -0.0017836433981459866
    - 0.15012577272667016
    - -0.0017253331680633845
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0.0537376513
    - 86.1824935
    - -1.33205849
    edge_std:
    - 21.576825529605706
    - 18.163155526935864
    - 0.18181337995282973
    - 0.12167075047864404
    - 0.2674056122223919
    - 0.12166926019859103
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 17.43921292
    - 36.19954752
    - 9.72246543
  _target_: datasets.garment_edge_dataset.GarmentEdgeDataset
  garment_particle_dir: /scratch/m000051/george/gcdv2/garment_particles_v2.1_11182025
  garment_edge_dir: /scratch/m000051/george/gcdv2/panel_edge_vecs
  gcd_dir: /scratch/m000051/george/gcdv2/garmentcodedatav2
  gcd_list_file: assets/gcd_list.txt
  n_samples: null
  n_points: 8196
  n_curves: 38
  n_panels: 37
  uv_only: false
  remove_bflag: false
  jitter_pcd_scale: 0
  jitter_uv_scale: 0
  absolute_coords: false
  random_dropout_scale: 0
  order_panels_by: 3d
  transformation_postfix: 11182025
  predict_rigid_transformations: true
  predict_attachment_type: true
  predict_stitch_tags: true
  predict_valid_mask: true
  collate_fn: null
model:
  _target_: models.lightningdit_edge_model_varlen.LightningCrossAttnDiTV3EdgeModelVarlen
  depth: 24
  hidden_size: 1024
  num_heads: 16
  use_qknorm: true
  use_swiglu: true
  use_rope: true
  use_rmsnorm: true
  wo_shift: false
  in_channels: 15
  use_checkpoint: false
  backend: flash-attn
  in_channels_context: 6
  n_panels: 37
  n_curves: 38
transport:
  _target_: transport.transport.Transport
  path_type: Linear
  model_type: velocity
  loss_type: null
  sample_eps: null
  train_eps: null
  use_cosine_loss: false
  use_lognorm: true
  denormalize_loss: false
  use_closure_loss: false
  use_valid_loss: false
sample:
  mode: ODE
  sampling_method: euler
  atol: 1.0e-06
  rtol: 0.001
  reverse: false
  likelihood: false
  num_sampling_steps: 250
  cfg_scale: 0
  per_proc_batch_size: 5
  fid_num: 5
  cfg_interval_start: 0.11
  timestep_shift: 0.3
  curve_sampling: false
  stitch_sampling: false
ckpt_path: null
data:
  val_split: assets/garment_particle_v2_test_11182025.txt
  train_split: assets/garment_particle_v2_train_11182025.txt
  workers_per_gpu: 8
  sampler: null
train:
  max_steps: 320000
  global_batch_size: 128
  global_seed: 0
  deterministic: false
  diff_seed: true
  exp_name: garment_edges_l_v2.2_everything
  wandb_dir: /scratch/m000051/george/InteractGarment
  wandb_cache_dir: /scratch/m000051/george/InteractGarment/cache
  wandb_project: interact-garment
  ckpt: null
  log_every: 10
  ckpt_every: 1000
  sample_every: 10000
  eval_every: 5000
  gradient_accumulation_steps: 1
  resume: outputs/garment_edges_l_v2.2_everything_cont/checkpoints
  weight_init: outputs/garment_edges_l_v2.2_everything_cont/checkpoints/0160000
  max_checkpoints: 2
  log_level: INFO
  mp_start_method: fork
  cudnn_benchmark: false
eval:
  sample_per_batch: 1
  n_samples: 4
  use_ema: true
  using_cfg: false
  evaluate: false
  mode: val
  custom_data_dir: null
optimizer:
  lr: 0.0001
  beta2: 0.99
  max_grad_norm: 1.0
  warmup_ratio: 0.01
  warmup_steps: 100
  weight_decay: 0
  param_groups: null
dist_params:
  backend: nccl
  timeout: 3600
fsdp:
  param_dtype: bfloat16
  reduce_dtype: float32
  reshard_after_forward: true
