defaults:
  - garment_particles_v2.2
  - _self_

_target_: datasets.garment_particle_v2_dataset_w_img_text.GarmentParticleDatasetV2WithImageText
gcd_list_file: assets/gcd_list.txt
gcd_dir: /scratch/m000051/george/gcdv2/garmentcodedatav2
text_path: /scratch/m000051/george/gcdv2/short_captions_v2.json
image_processor_name: facebook/dinov2-large
img_drop_prob: 0.1
text_drop_prob: 0.1
front_only: False
text_tokenizer_name: openai/clip-vit-large-patch14
text_max_length: 77
use_all_captions: False
pad_everything: True
front_back: False
